# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-09-20 01:05
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('theory', '0003_theory_tfile'),
    ]

    operations = [
        migrations.CreateModel(
            name='JuniorAnswer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=500, unique=True)),
                ('is_true', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='JuniorQuestion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=200, unique=True)),
                ('theme', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='theory.Theory')),
            ],
        ),
        migrations.CreateModel(
            name='ProfiQuestion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=200, unique=True)),
                ('answer', models.CharField(max_length=200)),
                ('theme', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='theory.Theory')),
            ],
        ),
        migrations.CreateModel(
            name='SeniorAnswer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=500, unique=True)),
                ('is_true', models.BooleanField(default=False)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ttest.JuniorQuestion')),
            ],
        ),
        migrations.CreateModel(
            name='SeniorQuestion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=200, unique=True)),
                ('theme', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='theory.Theory')),
            ],
        ),
        migrations.AddField(
            model_name='junioranswer',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ttest.JuniorQuestion'),
        ),
    ]
