# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-09-20 01:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ttest', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='junioranswer',
            name='text',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='juniorquestion',
            name='text',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='senioranswer',
            name='text',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='seniorquestion',
            name='text',
            field=models.CharField(max_length=200),
        ),
    ]
