# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-09-20 01:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ttest', '0002_auto_20160920_0140'),
    ]

    operations = [
        migrations.AlterField(
            model_name='juniorquestion',
            name='text',
            field=models.CharField(max_length=300),
        ),
    ]
