# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-09-20 02:00
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ttest', '0003_auto_20160920_0146'),
    ]

    operations = [
        migrations.AlterField(
            model_name='senioranswer',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ttest.SeniorQuestion'),
        ),
    ]
